// flow-typed signature: 5b9726106c05bba6930f8689b51ac9e5
// flow-typed version: <<STUB>>/mocha-pending_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-pending'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-pending' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mocha-pending/index' {
  declare module.exports: $Exports<'mocha-pending'>;
}
declare module 'mocha-pending/index.js' {
  declare module.exports: $Exports<'mocha-pending'>;
}
